### PR TITLE
case insensitive tag filtering

### PR DESCRIPTION
**Pull request by ryandillinfelton**
Mirroring the changes to the mapping and ingestion pipeline from redhatinsights/xjoin-search#125

### CODE REVIEW

**Comment by fijshion** [comment]
You'll need to change the default `ElasticSearchIndexTemplate` to add the new field since you changed the default pipeline template.

Also, getting this error when running the change locally (after adding the new field to the default ElasticSearchIndexTeamplate).

```
2021-11-12T08:14:58-05:00       ERROR   controller.xjoin-controller     Reconciler error        {"reconciler group": "xjoin.cloud.redhat.com", "reconciler kind": "XJoinPipeline", "name": "xjoinpipeline-sample", "namespace": "test", "error": "Elasticsearch API error: 400, {\"error\":{\"root_cause\":[{\"type\":\"parse_exception\",\"reason\":\"Failed to parse content to map\"}],\"type\":\"parse_exception\",\"reason\":\"Failed to parse content to map\",\"caused_by\":{\"type\":\"json_parse_exception\",\"reason\":\"Unexpected character ('c' (code 99)): was expecting comma to separate Object entries\\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@5efb1534; line: 1, column: 882]\"}},\"status\":400}"}
*errors.errorString Elasticsearch API error: 400, {"error":{"root_cause":[{"type":"parse_exception","reason":"Failed to parse content to map"}],"type":"parse_exception","reason":"Failed to parse content to map","caused_by":{"type":"json_parse_exception","reason":"Unexpected character ('c' (code 99)): was expecting comma to separate Object entries\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@5efb1534; line: 1, column: 882]"}},"status":400}
/home/chris/dev/projects/active/gopath/src/xjoin-operator/controllers/elasticsearch/elasticsearch.go:71 (0x1d00bb1)
        parseResponse: return res.StatusCode, nil, errors.Wrap(errors.New(
/home/chris/dev/projects/active/gopath/src/xjoin-operator/controllers/elasticsearch/pipeline.go:83 (0x1d03c1a)
        (*ElasticSearch).CreateESPipeline: statusCode, _, err := parseResponse(res)
/home/chris/dev/projects/active/gopath/src/xjoin-operator/controllers/xjoinpipeline_controller.go:250 (0x1d8990f)
        (*XJoinPipelineReconciler).Reconcile: err = i.ESClient.CreateESPipeline(pipelineVersion)
/home/chris/dev/projects/active/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:298 (0x1a77d09)
        (*Controller).reconcileHandler: if result, err := c.Do.Reconcile(ctx, req); err != nil {
/home/chris/dev/projects/active/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253 (0x1a7713a)
        (*Controller).processNextWorkItem: c.reconcileHandler(ctx, obj)
/home/chris/dev/projects/active/gopath/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216 (0x1a78f6a)
        (*Controller).Start.func1.2: for c.processNextWorkItem(ctx) {
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 (0x16d3b0b)
        JitterUntilWithContext.func1: JitterUntil(func() { f(ctx) }, period, jitterFactor, sliding, ctx.Done())
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:155 (0x16d3a83)
        BackoffUntil.func1: f()
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:156 (0x16d1eda)
        BackoffUntil: }()
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:133 (0x16d1e1f)
        JitterUntil: BackoffUntil(f, NewJitteredBackoffManager(period, jitterFactor, &clock.RealClock{}), sliding, stopCh)
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:185 (0x16d2135)
        JitterUntilWithContext: JitterUntil(func() { f(ctx) }, period, jitterFactor, sliding, ctx.Done())
/home/chris/dev/projects/active/gopath/pkg/mod/k8s.io/apimachinery@v0.20.2/pkg/util/wait/wait.go:99 (0x16d1d57)
        UntilWithContext: JitterUntilWithContext(ctx, f, period, 0.0, true)
/home/chris/.gvm/gos/go1.16.3/src/runtime/asm_amd64.s:1371 (0x47efa1)
        goexit: BYTE    $0x90   // NOP
```

**Comment by kruai** [comment]
Ryan's no longer here, but we still need this as it's blocking [an xjoin-search PR](https://github.com/RedHatInsights/xjoin-search/pull/125).
@fijshion would bug in this PR be easy for you to fix? If not, I can continue setting up a local env for xjoin-operator on my machine.

**Comment by fijshion** [comment]
@kruai I'm pretty loaded up with stuff to do. I could probably get to this in a couple days. Either way I think setting up the xjoin-operator dev environment is worthwhile.

**Comment by kruai** [comment]
OK, I'll work on it, then!

**Pull request closed without merging**
