### PR TITLE
Mapping updater

### PR DESCRIPTION
**Pull request by ryandillinfelton**
Here is an example of the [PR that get's created](https://github.com/ryandillinfelton/xjoin-operator/pull/14). The user the PR is opened by seems to be based on the token used, so in the redhatinsights version of the repo I'll make sure it uses dippy-bot's token or something like that

### CODE REVIEW

**Comment by ryandillinfelton** [comment]
:eyes:

**Comment by fijshion** [comment]
we're waiting on the performance tests to merge this in, right?

**Comment by ryandillinfelton** [comment]
> we're waiting on the performance tests to merge this in, right?

Yes. Also, is that force push going to make this super hard to merge now. It looks like there are a ton of new conflicts.

**Comment by fijshion** [comment]
it shouldn't be too hard since this change is isolated. You could always just create a new branch and copy your changes into it. The force push was necessary to remove some stuff from the git history before making the repo public.

**Comment by ryandillinfelton** [comment]
Closed this in favor of #8

**Pull request closed without merging**
