### PR TITLE
Deploy apicurio via clowder in setup-clowder.sh

### PR DESCRIPTION
**Pull request by fijshion**

### CODE REVIEW

**Comment by skateman** [comment]
Looks good, but I think the README should be updated [here](https://github.com/RedHatInsights/xjoin-operator#local-development)

**Comment by fijshion** [comment]
updated

**Review by skateman — APPROVED** [review]
The Seal of Approval

**Review by jpramos123 — CHANGES_REQUESTED** [review]
@skateman We may correct the `forward-ports-clowder.sh` script as well:

https://github.com/RedHatInsights/xjoin-operator/blob/1eb7d6ddada911f510693d3da836f92548b0fe91/dev/forward-ports-clowder.sh#L21

Thanks

**Comment by fijshion** [comment]
@jpramos123 fixed the forward-ports-clowder script in the latest push

**Review by jpramos123 — APPROVED** [review]

**Review by thearifismail — APPROVED** [review]

**Pull request merged**
